name: Build Android APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev cmake openjdk-17-jdk unzip
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          # Aceitar licenças do Android SDK automaticamente
          yes | buildozer android debug
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Identificador-Animais-APK
          path: bin/*.apk
